### ISSUE TITLE
show_crossed_off not working and crossed off items not being lined through

### ISSUE THREAD

**Issue by dfmckay** [ljmerza/our-groceries-card#11]
I can't get 'show_crossed_off: false' to work and the crossed offed items don't show the line through. I am using 0.108.6 home assistant core in a docker container on a NUC. I have attempted both the default theme and other themes, all are experiencing the same behavior. When I do cross them off either with the app or in home assistant it moved the item down and marks it correctly in the app.

**Comment by svenugop** [comment]
I am facing the same problem. Running HA on a raspberry pi

**Comment by kbrohkahn** [comment]
Same

**Comment by bruhnsp** [comment]
Same for me too.

**Comment by jesse-projects** [comment]
I'm seeing the same behavior. Detailed installation information below

### System Health:

| Key | Value |
| --- | --- |
| arch | x86_64 |
| chassis | laptop |
| dev | false |
| docker | true |
| docker_version | 19.03.11 |
| hassio | true |
| host_os | Ubuntu 18.04.4 LTS |
| installation_type | Home Assistant Supervised |
| os_name | Linux |
| os_version | 4.15.0-109-generic |
| python_version | 3.8.3 |
| supervisor | 229 |
| timezone | America/Los_Angeles |
| version | 0.113.0 |
| virtualenv | false |

### HACS Info:

| Integration version: | 1.3.2 |
| --- | --- |
| Frontend version: | 202008041812 |
| Repositories: | 655 |
| Installed repositories: | 17 |

### Our Groceries Integration & Card:

| Key | Value |
| --- | --- |
| Integration/Sensor Version: | 1.3.5 |
| Card Version: | 1.4.0 |

**Comment by IWIK-Apps** [comment]
Same here, any resolution? running on Proxmox

**Comment by kbrohkahn** [comment]
I did some reverse engineering to find the issue, it's with the Python library this plugin is using:
https://github.com/ljmerza/py-our-groceries/issues/9#issue-737271176. Hopefully @ljmerza can take a look since it should be a 1-line fix.

**Comment by IWIK-Apps** [comment]
> 
> 
> I did some reverse engineering to find the issue, it's with the Python library this plugin is using:
> [ljmerza/py-our-groceries#9 (comment)](https://github.com/ljmerza/py-our-groceries/issues/9#issue-737271176). Hopefully @ljmerza can take a look since it should be a 1-line fix.

Anyway we can change the one line in our custom component ourselves?

**Comment by ffrederiksen** [comment]
Same issue here, running on Docker

**Comment by floydheld** [comment]
I tried to fix the code, but no luck... a lot of code and little understanding on my side...
Anyone any luck? If so, please post your findings?

**Comment by ljmerza** [comment]
just updated the OG python library and OG integration to point to the new library version. This should fix it. sorry it took so long, I dont have the free time i used to right now. let me know if this fixes it and ill close out

**Comment by IWIK-Apps** [comment]
Issue remains? I believe, I haven't had it installed since trying before, but it still shows crossed off items always

**Comment by dfmckay** [comment]
I updated it to the master build via hacs and it has fixed the issue. Thank you very much.

**Comment by kejXero** [comment]
Could you please elaborate on how you did perform the update.

I could not see any updates in HACS, so I tried an reinstallation without success.

Thanks in advance.

With best regards Henrik

**Comment by kejXero** [comment]
It is working now. HACS suddenly showed Ourgrocerie was up for an update. Everything is fine.

Hent Outlook til Android<https://aka.ms/ghei36>

________________________________
From: Henrik Næsby <henriknaesby@outlook.dk>
Sent: Thursday, February 11, 2021 3:24:14 PM
To: ljmerza/our-groceries-card <reply@reply.github.com>; ljmerza/our-groceries-card <our-groceries-card@noreply.github.com>
Cc: Manual <manual@noreply.github.com>
Subject: RE: [ljmerza/our-groceries-card] show_crossed_off not working and crossed off items not being lined through (#11)


Could you please elaborate on how you did perform the update.



I could not see any updates in HACS, so I tried an reinstallation without success.



Thanks in advance.



With best regards Henrik

**Comment by dykandDK** [comment]
The issue was fixed but seems to be back with the latest update of the custom integration (ha-our-groceries). 

At least for me, I am now seeing crossed-off items in the list again.

Anyone else having this issue?

**Comment by kejXero** [comment]
Yes i am also seeing crossed off items as non crossed off. Latest HA 2021.4.4

**Comment by ljmerza** [comment]
should be fixed in the latest our-groceries integration

**Comment by kejXero** [comment]
Correct, it was previously working, but now the error is current. I see no crossed out items on my list any more. Only clear letters, though the lines are moving up and down when i click on them as if i was checking them off or on in the list. The issue is not fixed.

**Comment by kejXero** [comment]
Updated to version 1.16 today. Issue is still valid. No items is shown as crossed off.

**Comment by ljmerza** [comment]
you need to update the integration

**Comment by kejXero** [comment]
Could you help.me with some guide lines? I performed my update via HACS. where do I update the integration?

**Comment by dfmckay** [comment]
in HACS click on integrations and search for Our Groceries. Then click the 3 dots under the integration and hit update information. That should refresh hacs and give you the option to update it. The Current version as of apr 15th is 1.3.9. The update does fix the issue.

**Comment by kejXero** [comment]
Don't know how, but updated from 1.3.8 to 1.3.9 and now everything is fine. Text is shown with crossed off items. Thanks
